import httpx
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from utils.config import API_URL
import pandas_ta as ta
import asyncio
import time

class MLPredictor:
    def __init__(self):
        self.models = {}  # Store models per symbol
        self.last_trained = {} # Store last training time per symbol

    async def fetch_historical_data(self, client, symbol, interval="15m", limit=1000):
        try:
            res = await client.get(
                f"{API_URL}/fapi/v1/klines",
                params={"symbol": symbol, "interval": interval, "limit": limit},
                timeout=15
            )
            if res.status_code == 200:
                df = pd.DataFrame(res.json()).iloc[:, [0, 1, 2, 3, 4, 5]]
                df.columns = ["ot", "o", "h", "l", "c", "v"]
                for col in ["o", "h", "l", "c", "v"]:
                    df[col] = df[col].astype(float)
                return df
            return None
        except Exception as e:
            print(f"Error fetching data for ML {symbol}: {e}")
            return None

    def feature_engineering(self, df):
        # Technical indicators as features
        df['ema_9'] = ta.ema(df['c'], length=9)
        df['ema_21'] = ta.ema(df['c'], length=21)
        df['rsi'] = ta.rsi(df['c'], length=14)
        df['atr'] = ta.atr(df['h'], df['l'], df['c'], length=14)
        
        macd = ta.macd(df['c'], fast=12, slow=26, signal=9)
        if macd is not None:
            df = pd.concat([df, macd], axis=1)
        
        # Price and volume rates of change
        df['roc_c'] = df['c'].pct_change()
        df['roc_v'] = df['v'].pct_change()
        
        # Volatility
        df['volatility'] = (df['h'] - df['l']) / df['c']
        
        # Drop NaN values generated by indicators
        df.dropna(inplace=True)
        return df

    def create_labels(self, df, lookahead=4, threshold=0.005):
        # Target: Price movement in the next 'lookahead' candles
        # 1 if price goes up by > threshold, 0 otherwise
        future_returns = df['c'].shift(-lookahead) / df['c'] - 1
        df['target'] = (future_returns > threshold).astype(int)
        
        # Drop rows where target is NaN (the last 'lookahead' rows)
        df.dropna(subset=['target'], inplace=True)
        return df

    async def train_model(self, client, symbol):
        df = await self.fetch_historical_data(client, symbol, interval="15m", limit=1000)
        if df is None or df.empty:
            return False

        df = self.feature_engineering(df)
        df = self.create_labels(df)

        if len(df) < 100:
            return False

        # Prepare features (X) and target (y)
        features = ['ema_9', 'ema_21', 'rsi', 'atr', 'roc_c', 'roc_v', 'volatility']
        # Add macd columns if they exist
        features.extend([col for col in df.columns if 'MACD' in col])
        
        X = df[features]
        y = df['target']

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

        # Train XGBoost
        model = xgb.XGBClassifier(
            n_estimators=100,
            learning_rate=0.05,
            max_depth=4,
            random_state=42,
            eval_metric='logloss'
        )
        
        model.fit(X_train, y_train)
        
        self.models[symbol] = model
        self.last_trained[symbol] = time.time()
        return True

    async def predict(self, client, symbol, current_df):
        # Retrain model if not exists or older than 12 hours
        now = time.time()
        if symbol not in self.models or (now - self.last_trained.get(symbol, 0)) > 43200:
            success = await self.train_model(client, symbol)
            if not success:
                return 0.5 # Neutral probability

        model = self.models.get(symbol)
        if model is None:
            return 0.5

        df = current_df.copy()
        df = self.feature_engineering(df)
        
        if df.empty:
            return 0.5

        features = ['ema_9', 'ema_21', 'rsi', 'atr', 'roc_c', 'roc_v', 'volatility']
        features.extend([col for col in df.columns if 'MACD' in col])
        
        X_live = df[features].iloc[[-1]]
        
        # Predict probability of class 1 (UP)
        prob = model.predict_proba(X_live)[0][1]
        return prob

ml_predictor = MLPredictor()
